codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%

# NOTE: src/html/bindings.rs is currently excluded from Codecov checks
# because this module is not tested yet.
ignore:
  - "src/html/bindings.rs"
  - "crates/bevy_extended_ui_macros/src/lib.rs"
  - "src/example_utils.rs"
  - "src/utils.rs"
  # Widget files with heavy runtime/UI interaction paths are excluded for now.
  # Covered widget core files remain included (e.g. mod.rs, validation.rs, widget_util.rs).
  - "src/widgets/body.rs"
  - "src/widgets/div.rs"
  - "src/widgets/form.rs"
  - "src/widgets/content/divider.rs"
  - "src/widgets/content/headline.rs"
  - "src/widgets/content/image.rs"
  - "src/widgets/content/paragraph.rs"
  - "src/widgets/content/tooltip.rs"
  - "src/widgets/controls/button.rs"
  - "src/widgets/controls/check_box.rs"
  - "src/widgets/controls/choice_box.rs"
  - "src/widgets/controls/color_picker.rs"
  - "src/widgets/controls/date_picker.rs"
  - "src/widgets/controls/fieldset.rs"
  - "src/widgets/controls/input.rs"
  - "src/widgets/controls/progress_bar.rs"
  - "src/widgets/controls/radio_button.rs"
  - "src/widgets/controls/scroll_bar.rs"
  - "src/widgets/controls/slider.rs"
  - "src/widgets/controls/switch_button.rs"
  - "src/widgets/controls/toggle_button.rs"
